//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aoc2022.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aoc2022.Tests.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7896
        ///4992
        ///1382
        ///2920
        ///7533
        ///2709
        ///6020
        ///5321
        ///2698
        ///6806
        ///8008
        ///
        ///1340
        ///1472
        ///7147
        ///2707
        ///5491
        ///7003
        ///2337
        ///1401
        ///5309
        ///4385
        ///2805
        ///
        ///6019
        ///1924
        ///8917
        ///6303
        ///9358
        ///3640
        ///1563
        ///1902
        ///
        ///10946
        ///10333
        ///8504
        ///6110
        ///10157
        ///
        ///4578
        ///1711
        ///3343
        ///6159
        ///4045
        ///3487
        ///3070
        ///5663
        ///3518
        ///5839
        ///5911
        ///4970
        ///4852
        ///4512
        ///
        ///4277
        ///3324
        ///6172
        ///8272
        ///2707
        ///3292
        ///6599
        ///1204
        ///7030
        ///3075
        ///
        ///6907
        ///5595
        ///10251
        ///8654
        ///4036
        ///11545
        ///
        ///16787
        ///11035
        ///12217
        ///
        ///2196
        ///1519
        ///5810
        ///6837
        ///1193
        ///6480
        ///1237
        ///1659
        ///4323
        ///2896
        ///3878
        ///2894
        ///
        ///15886
        ///20356
        ///23636
        ///
        ///8795
        ///7986
        ///14228
        ///15738
        ///13503
        ///
        ///6598
        ///17951
        ///17508
        ///2446
        ///
        ///1382
        ///3232
        ///6467
        ///2791
        ///6250 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CaloriesCountingInput {
            get {
                return ResourceManager.GetString("CaloriesCountingInput", resourceCulture);
            }
        }
    }
}
