//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aoc2022.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aoc2022.Tests.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7896
        ///4992
        ///1382
        ///2920
        ///7533
        ///2709
        ///6020
        ///5321
        ///2698
        ///6806
        ///8008
        ///
        ///1340
        ///1472
        ///7147
        ///2707
        ///5491
        ///7003
        ///2337
        ///1401
        ///5309
        ///4385
        ///2805
        ///
        ///6019
        ///1924
        ///8917
        ///6303
        ///9358
        ///3640
        ///1563
        ///1902
        ///
        ///10946
        ///10333
        ///8504
        ///6110
        ///10157
        ///
        ///4578
        ///1711
        ///3343
        ///6159
        ///4045
        ///3487
        ///3070
        ///5663
        ///3518
        ///5839
        ///5911
        ///4970
        ///4852
        ///4512
        ///
        ///4277
        ///3324
        ///6172
        ///8272
        ///2707
        ///3292
        ///6599
        ///1204
        ///7030
        ///3075
        ///
        ///6907
        ///5595
        ///10251
        ///8654
        ///4036
        ///11545
        ///
        ///16787
        ///11035
        ///12217
        ///
        ///2196
        ///1519
        ///5810
        ///6837
        ///1193
        ///6480
        ///1237
        ///1659
        ///4323
        ///2896
        ///3878
        ///2894
        ///
        ///15886
        ///20356
        ///23636
        ///
        ///8795
        ///7986
        ///14228
        ///15738
        ///13503
        ///
        ///6598
        ///17951
        ///17508
        ///2446
        ///
        ///1382
        ///3232
        ///6467
        ///2791
        ///6250 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CaloriesCountingInput {
            get {
                return ResourceManager.GetString("CaloriesCountingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-66,23-25
        ///3-3,2-80
        ///14-80,13-20
        ///39-78,40-40
        ///36-90,89-90
        ///51-94,50-50
        ///10-72,10-98
        ///54-81,2-90
        ///27-84,27-85
        ///21-57,21-57
        ///6-55,4-5
        ///80-87,87-90
        ///23-71,22-90
        ///24-37,2-36
        ///79-91,78-91
        ///75-92,91-93
        ///23-80,23-81
        ///67-94,68-94
        ///79-85,79-81
        ///40-88,39-89
        ///15-75,14-76
        ///18-77,34-78
        ///2-99,4-93
        ///1-74,15-75
        ///39-82,39-81
        ///19-91,18-84
        ///56-87,57-86
        ///15-72,14-71
        ///37-88,36-87
        ///21-24,18-23
        ///34-83,34-34
        ///20-95,94-95
        ///27-75,26-80
        ///91-93,27-92
        ///55-66,56-62
        ///29-31,30-89
        ///85-95,89-99
        ///1-2,1-3
        ///63-64,13-64
        ///66-95,30-86
        ///2-73,3-74
        ///25-99,6-25
        ///10-28,28-87
        ///10-42,9-43
        ///12- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CampCleanupInput {
            get {
                return ResourceManager.GetString("CampCleanupInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Y
        ///B Z
        ///B Z
        ///C Y
        ///B Y
        ///C Z
        ///C Z
        ///C Y
        ///B Z
        ///C Z
        ///C X
        ///C Y
        ///C Z
        ///C Y
        ///C Y
        ///B Z
        ///A Y
        ///C Z
        ///C Z
        ///C Z
        ///B X
        ///B Z
        ///C Y
        ///A X
        ///C X
        ///C Z
        ///C Y
        ///C Z
        ///C Z
        ///C Z
        ///C Y
        ///C Y
        ///A X
        ///C X
        ///C Z
        ///B Z
        ///B Z
        ///B Z
        ///B Z
        ///C Z
        ///C Y
        ///C Z
        ///B Z
        ///A Y
        ///A X
        ///C Z
        ///C Y
        ///C Z
        ///C Y
        ///C Z
        ///A X
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///C Y
        ///C Y
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///B X
        ///C Y
        ///B Y
        ///B X
        ///A X
        ///C Y
        ///C Z
        ///C Z
        ///C Y
        ///C Z
        ///C Z
        ///A Y
        ///C Y
        ///C Z
        ///C Y
        ///B Z
        ///C Z
        ///C Y
        ///B Z
        ///B Z
        ///C Z
        ///C Y
        ///C Y
        ///C Z
        ///C Z
        ///C Y
        ///C Z
        ///C Y
        ///C Y
        ///C Y
        ///C Y
        ///B X
        ///C Z
        ///C Z
        ///C X
        ///C X
        ///C Z
        ///B Z
        ///A Y
        ///C Y
        ///A Y
        ///C Y
        ///C Z
        ///C Y
        ///C Z
        ///C Y
        ///B Z
        ///C Z
        ///C Z
        ///C Y
        ///A Y
        ///C Z
        ///B Z
        ///C Z
        ///C Z
        ///C X
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///B Z
        ///C Z
        ///C Y
        ///B Z
        ///C Y
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RockPaperScissorsInput {
            get {
                return ResourceManager.GetString("RockPaperScissorsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mjpsHcssDzLTzMsz
        ///tFhbtClRVtbhRCGBFntNTrLhqrwqWMDMTWTqMq
        ///LltbngLGRSBgSgGRCJdSdQHvdfmQccmjSQ
        ///lBslsZDDWdGdGpSMts
        ///grQhDvqLQHDNGJJtbRMQQJ
        ///HChCTnnLCgCrTZPPFzzVPcVD
        ///ShrzjhNGrNqrhWnHHfVHbhnHbbhH
        ///RBsvcBcDCdsRTsvgCgcPFRQpVQGQJPVFbnJfbJ
        ///DvsTsdlCBsGLrjzmlqqz
        ///WJJqZTgCnBLGCZBJCJnTLggTDDSDDMNdDSdbdSSsWDFfMsFf
        ///PVjqpVHmPpvmcjhrRprFmQQffbfNbQMMsSMQNQ
        ///cwcpRvrVlVgwtBwZqBzZ
        ///qfJJmpqpmhsggvvpVPZCrhdFLFzZFDdLLh
        ///CtCTBctGcGLSzZddGZSW
        ///RlNjBCnjttBHHMMcQHCsRfsbfwgggmmJvmgfpm
        ///ZmcgBBZhZMsnqnCPjpHPjLHp
        ///dGbNwNtlTMTzGfNvTvdwNGVLPpQHPjLQPCpC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RucksackReorganizationInput {
            get {
                return ResourceManager.GetString("RucksackReorganizationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 [B]     [L]     [S]
        ///        [Q] [J] [C]     [W]     [F]
        ///    [F] [T] [B] [D]     [P]     [P]
        ///    [S] [J] [Z] [T]     [B] [C] [H]
        ///    [L] [H] [H] [Z] [G] [Z] [G] [R]
        ///[R] [H] [D] [R] [F] [C] [V] [Q] [T]
        ///[C] [J] [M] [G] [P] [H] [N] [J] [D]
        ///[H] [B] [R] [S] [R] [T] [S] [R] [L]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 8 from 7 to 1
        ///move 9 from 1 to 9
        ///move 4 from 5 to 4
        ///move 4 from 6 to 1
        ///move 3 from 8 to 5
        ///move 6 from 5 to 9
        ///move 1 from 5 to 1
        ///move 4 from 4 to 9
        ///move 7 from 3 to 7
        ///move 6 from 7 to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupplyStacksInput {
            get {
                return ResourceManager.GetString("SupplyStacksInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzsspbssbhshchmmrmprmrfrsfrrjhjphjjtppbfflqfqppdhdbhdhbbjgghgzgsgfsfhfhvvwcwhwwnppsbsggqnnvvtffpssjfjnnltntdtdddptprppjmmqssrlrplllfrrzggbmmlmnmtnnzddfdgfdfsstbstbbzcbbcjcvvfwwwzlzssglsgllnbnmbnmbbgmmppmwwsrrzqqvgqgnqnmmswwrnnbsnnbdbwwqnwqnwwzzqwzqzjqqwbqbccjcwwjlwjwppqfqjffwddrzrjzrjzzzhchjjlqqrggzvvnlvnvjvhvnvjvbbvdvldldbbwddtsscbbhccmbmbppbmmgjggcjjlrrwjwtjwwmffgddwvdvbdbvvhchmhmdmwwbjbjcbbcmbmmslmlslsjjrnrjrjpjcjgcjcjbbwsbsbfssjzsjsggcmcsswgssbbqpbqqdsdqqztzmzpmpbmbvbjjtrjtthwhbhnbhnbnssvpvsppgrrcwrrmqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TuningTroubleInput {
            get {
                return ResourceManager.GetString("TuningTroubleInput", resourceCulture);
            }
        }
    }
}
