//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aoc2022.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aoc2022.Tests.Resources.ResourceFiles", typeof(ResourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7896
        ///4992
        ///1382
        ///2920
        ///7533
        ///2709
        ///6020
        ///5321
        ///2698
        ///6806
        ///8008
        ///
        ///1340
        ///1472
        ///7147
        ///2707
        ///5491
        ///7003
        ///2337
        ///1401
        ///5309
        ///4385
        ///2805
        ///
        ///6019
        ///1924
        ///8917
        ///6303
        ///9358
        ///3640
        ///1563
        ///1902
        ///
        ///10946
        ///10333
        ///8504
        ///6110
        ///10157
        ///
        ///4578
        ///1711
        ///3343
        ///6159
        ///4045
        ///3487
        ///3070
        ///5663
        ///3518
        ///5839
        ///5911
        ///4970
        ///4852
        ///4512
        ///
        ///4277
        ///3324
        ///6172
        ///8272
        ///2707
        ///3292
        ///6599
        ///1204
        ///7030
        ///3075
        ///
        ///6907
        ///5595
        ///10251
        ///8654
        ///4036
        ///11545
        ///
        ///16787
        ///11035
        ///12217
        ///
        ///2196
        ///1519
        ///5810
        ///6837
        ///1193
        ///6480
        ///1237
        ///1659
        ///4323
        ///2896
        ///3878
        ///2894
        ///
        ///15886
        ///20356
        ///23636
        ///
        ///8795
        ///7986
        ///14228
        ///15738
        ///13503
        ///
        ///6598
        ///17951
        ///17508
        ///2446
        ///
        ///1382
        ///3232
        ///6467
        ///2791
        ///6250 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CaloriesCountingInput {
            get {
                return ResourceManager.GetString("CaloriesCountingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-66,23-25
        ///3-3,2-80
        ///14-80,13-20
        ///39-78,40-40
        ///36-90,89-90
        ///51-94,50-50
        ///10-72,10-98
        ///54-81,2-90
        ///27-84,27-85
        ///21-57,21-57
        ///6-55,4-5
        ///80-87,87-90
        ///23-71,22-90
        ///24-37,2-36
        ///79-91,78-91
        ///75-92,91-93
        ///23-80,23-81
        ///67-94,68-94
        ///79-85,79-81
        ///40-88,39-89
        ///15-75,14-76
        ///18-77,34-78
        ///2-99,4-93
        ///1-74,15-75
        ///39-82,39-81
        ///19-91,18-84
        ///56-87,57-86
        ///15-72,14-71
        ///37-88,36-87
        ///21-24,18-23
        ///34-83,34-34
        ///20-95,94-95
        ///27-75,26-80
        ///91-93,27-92
        ///55-66,56-62
        ///29-31,30-89
        ///85-95,89-99
        ///1-2,1-3
        ///63-64,13-64
        ///66-95,30-86
        ///2-73,3-74
        ///25-99,6-25
        ///10-28,28-87
        ///10-42,9-43
        ///12- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CampCleanupInput {
            get {
                return ResourceManager.GetString("CampCleanupInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addx 1
        ///noop
        ///addx 4
        ///noop
        ///noop
        ///noop
        ///addx 6
        ///addx -1
        ///addx 5
        ///noop
        ///noop
        ///noop
        ///addx 5
        ///addx -14
        ///noop
        ///addx 19
        ///noop
        ///addx 1
        ///addx 4
        ///addx 1
        ///noop
        ///noop
        ///addx 2
        ///addx 5
        ///addx -27
        ///addx 20
        ///addx -30
        ///addx 2
        ///addx 5
        ///addx 2
        ///addx 4
        ///addx -3
        ///addx 2
        ///addx 5
        ///addx 2
        ///addx -9
        ///addx 1
        ///addx 11
        ///noop
        ///addx -20
        ///addx 7
        ///addx 23
        ///addx 2
        ///addx 3
        ///addx -2
        ///addx -34
        ///addx -2
        ///noop
        ///addx 3
        ///noop
        ///addx 3
        ///addx 2
        ///noop
        ///addx 3
        ///addx 2
        ///addx 5
        ///addx 2
        ///addx -9
        ///addx -7
        ///addx 21
        ///noop
        ///addx 8
        ///noop
        ///addx -1
        ///addx 3
        ///addx -2
        ///addx 5
        ///addx -37
        ///noop
        ///addx 35
        ///addx -31
        ///addx 1
        ///addx 4
        ///addx -1
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CathodeRayTubeInput {
            get {
                return ResourceManager.GetString("CathodeRayTubeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcccccaaaaaacccaaaccaaaaaaaacccaaaaaaccccccccccccccccccccccccccccaaaaaaaaaaaaaacacccccccccccccccccccccccccccccccaaaaaaaacccccccccccccccccccccccccccccccccccccccccccccaaaaa
        ///abcccccaaaaaaaacaaaaccaaaaaaccccaaaaaaccccccccccaaacccccccccccccccaaaaaaaaaaaaaaaacccccccccccccccccccccccccccccccaaaaaaaaaccccccaaaccccccccccccccccccccccccccccccccccaaaaaa
        ///abccccaaaaaaaaacaaaaccaaaaaaccccaaaaaaaaccccccccaaaccccccccccccccccaaaaaaaaaaaaaaccccaaaccccccccccccccccccccccccccaaaaaaaaccccacaaaccccccccccccccccaaccccccccccccccccaaa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HillClimbingAlgorithmInput {
            get {
                return ResourceManager.GetString("HillClimbingAlgorithmInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey 0:
        ///  Starting items: 89, 84, 88, 78, 70
        ///  Operation: new = old * 5
        ///  Test: divisible by 7
        ///    If true: throw to monkey 6
        ///    If false: throw to monkey 7
        ///
        ///Monkey 1:
        ///  Starting items: 76, 62, 61, 54, 69, 60, 85
        ///  Operation: new = old + 1
        ///  Test: divisible by 17
        ///    If true: throw to monkey 0
        ///    If false: throw to monkey 6
        ///
        ///Monkey 2:
        ///  Starting items: 83, 89, 53
        ///  Operation: new = old + 8
        ///  Test: divisible by 11
        ///    If true: throw to monkey 5
        ///    If false: throw to monkey 3
        ///
        ///Monkey 3:
        ///  Starting items: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonkeyInTheMiddleInput {
            get {
                return ResourceManager.GetString("MonkeyInTheMiddleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir jmtrrrp
        ///dir jssnn
        ///dir lbrmb
        ///11968 pcccp
        ///$ cd jmtrrrp
        ///$ ls
        ///77968 chq.jvb
        ///dir fmgsql
        ///$ cd fmgsql
        ///$ ls
        ///dir dbnsfp
        ///dir vvp
        ///$ cd dbnsfp
        ///$ ls
        ///51021 crlq.lrj
        ///186829 dhcrzvbr.wmn
        ///16232 fvhn.fqm
        ///54150 qpbqqj.rpg
        ///$ cd ..
        ///$ cd vvp
        ///$ ls
        ///179105 rrcsndz.tzp
        ///$ cd ..
        ///$ cd ..
        ///$ cd ..
        ///$ cd jssnn
        ///$ ls
        ///dir bphfqs
        ///dir dbnsfp
        ///dir pcccp
        ///dir snr
        ///dir zjbvwsnv
        ///$ cd bphfqs
        ///$ ls
        ///110077 dhcrzvbr.wmn
        ///$ cd ..
        ///$ cd dbnsfp
        ///$ ls
        ///dir hgvh
        ///dir jtqdcmsz
        ///154197 rrcsndz.tzp
        ///$ cd hgvh
        ///$ ls
        ///dir qjnbg
        ///$ cd qjnbg
        ///$ ls
        ///dir bqzfpr
        ///$ cd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoSizeLeftOnDeviceInput {
            get {
                return ResourceManager.GetString("NoSizeLeftOnDeviceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Y
        ///B Z
        ///B Z
        ///C Y
        ///B Y
        ///C Z
        ///C Z
        ///C Y
        ///B Z
        ///C Z
        ///C X
        ///C Y
        ///C Z
        ///C Y
        ///C Y
        ///B Z
        ///A Y
        ///C Z
        ///C Z
        ///C Z
        ///B X
        ///B Z
        ///C Y
        ///A X
        ///C X
        ///C Z
        ///C Y
        ///C Z
        ///C Z
        ///C Z
        ///C Y
        ///C Y
        ///A X
        ///C X
        ///C Z
        ///B Z
        ///B Z
        ///B Z
        ///B Z
        ///C Z
        ///C Y
        ///C Z
        ///B Z
        ///A Y
        ///A X
        ///C Z
        ///C Y
        ///C Z
        ///C Y
        ///C Z
        ///A X
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///C Y
        ///C Y
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///B X
        ///C Y
        ///B Y
        ///B X
        ///A X
        ///C Y
        ///C Z
        ///C Z
        ///C Y
        ///C Z
        ///C Z
        ///A Y
        ///C Y
        ///C Z
        ///C Y
        ///B Z
        ///C Z
        ///C Y
        ///B Z
        ///B Z
        ///C Z
        ///C Y
        ///C Y
        ///C Z
        ///C Z
        ///C Y
        ///C Z
        ///C Y
        ///C Y
        ///C Y
        ///C Y
        ///B X
        ///C Z
        ///C Z
        ///C X
        ///C X
        ///C Z
        ///B Z
        ///A Y
        ///C Y
        ///A Y
        ///C Y
        ///C Z
        ///C Y
        ///C Z
        ///C Y
        ///B Z
        ///C Z
        ///C Z
        ///C Y
        ///A Y
        ///C Z
        ///B Z
        ///C Z
        ///C Z
        ///C X
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///C Z
        ///B Z
        ///C Z
        ///C Y
        ///B Z
        ///C Y
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RockPaperScissorsInput {
            get {
                return ResourceManager.GetString("RockPaperScissorsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 1
        ///L 1
        ///U 1
        ///L 2
        ///U 2
        ///D 2
        ///U 1
        ///R 1
        ///D 1
        ///R 2
        ///D 1
        ///U 1
        ///D 2
        ///R 2
        ///L 2
        ///R 2
        ///D 2
        ///R 2
        ///D 1
        ///L 2
        ///U 1
        ///R 2
        ///U 1
        ///L 1
        ///D 1
        ///R 1
        ///L 1
        ///D 2
        ///L 2
        ///U 1
        ///R 1
        ///L 2
        ///U 2
        ///D 2
        ///L 2
        ///R 1
        ///L 2
        ///U 2
        ///L 2
        ///D 2
        ///U 2
        ///D 1
        ///L 2
        ///D 1
        ///L 1
        ///D 2
        ///R 1
        ///D 1
        ///R 2
        ///D 2
        ///U 2
        ///D 2
        ///L 1
        ///R 1
        ///D 1
        ///L 1
        ///U 1
        ///L 2
        ///R 1
        ///U 2
        ///L 1
        ///D 2
        ///L 1
        ///D 2
        ///U 1
        ///L 1
        ///D 1
        ///R 2
        ///L 2
        ///R 2
        ///L 2
        ///D 1
        ///U 2
        ///L 1
        ///U 1
        ///R 2
        ///D 1
        ///R 2
        ///L 2
        ///D 1
        ///R 2
        ///U 1
        ///D 1
        ///L 2
        ///R 1
        ///U 1
        ///D 1
        ///L 2
        ///D 1
        ///L 2
        ///U 2
        ///R 1
        ///L 1
        ///D 2
        ///U 1
        ///D 1
        ///U 1
        ///R 2
        ///L 2
        ///R 2
        ///L 2
        ///U 2
        ///L 1
        ///U 1
        ///L 2
        ///R 2
        ///L 1
        ///U 1
        ///R 2
        ///U 1
        ///L 2
        ///D 1
        ///U 2
        ///D 1
        ///L 1
        ///U 3
        ///D 3
        ///L 1
        ///D 1
        ///L 2
        ///D 1
        ///R 2
        ///U 1
        ///D 3
        ///R 1
        ///U 1
        ///D 2
        ///U 3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RopeBridgeInput {
            get {
                return ResourceManager.GetString("RopeBridgeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mjpsHcssDzLTzMsz
        ///tFhbtClRVtbhRCGBFntNTrLhqrwqWMDMTWTqMq
        ///LltbngLGRSBgSgGRCJdSdQHvdfmQccmjSQ
        ///lBslsZDDWdGdGpSMts
        ///grQhDvqLQHDNGJJtbRMQQJ
        ///HChCTnnLCgCrTZPPFzzVPcVD
        ///ShrzjhNGrNqrhWnHHfVHbhnHbbhH
        ///RBsvcBcDCdsRTsvgCgcPFRQpVQGQJPVFbnJfbJ
        ///DvsTsdlCBsGLrjzmlqqz
        ///WJJqZTgCnBLGCZBJCJnTLggTDDSDDMNdDSdbdSSsWDFfMsFf
        ///PVjqpVHmPpvmcjhrRprFmQQffbfNbQMMsSMQNQ
        ///cwcpRvrVlVgwtBwZqBzZ
        ///qfJJmpqpmhsggvvpVPZCrhdFLFzZFDdLLh
        ///CtCTBctGcGLSzZddGZSW
        ///RlNjBCnjttBHHMMcQHCsRfsbfwgggmmJvmgfpm
        ///ZmcgBBZhZMsnqnCPjpHPjLHp
        ///dGbNwNtlTMTzGfNvTvdwNGVLPpQHPjLQPCpC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RucksackReorganizationInput {
            get {
                return ResourceManager.GetString("RucksackReorganizationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 [B]     [L]     [S]
        ///        [Q] [J] [C]     [W]     [F]
        ///    [F] [T] [B] [D]     [P]     [P]
        ///    [S] [J] [Z] [T]     [B] [C] [H]
        ///    [L] [H] [H] [Z] [G] [Z] [G] [R]
        ///[R] [H] [D] [R] [F] [C] [V] [Q] [T]
        ///[C] [J] [M] [G] [P] [H] [N] [J] [D]
        ///[H] [B] [R] [S] [R] [T] [S] [R] [L]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 8 from 7 to 1
        ///move 9 from 1 to 9
        ///move 4 from 5 to 4
        ///move 4 from 6 to 1
        ///move 3 from 8 to 5
        ///move 6 from 5 to 9
        ///move 1 from 5 to 1
        ///move 4 from 4 to 9
        ///move 7 from 3 to 7
        ///move 6 from 7 to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SupplyStacksInput {
            get {
                return ResourceManager.GetString("SupplyStacksInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001012002320230123321232210301123012330310002132422435543131011222140442223410333011301131030221102
        ///210021010313032103103140242443030204041353523334411152343535155001331010424342400321222130332211000
        ///220111020130022123343304003244321141423124554224223425242425411232310410220404123040022230232012001
        ///110001322300033003110104022024431213325443435243534332232113223514234032203314213003023330320211122
        ///222202032101012330012433332004525555532223225141422352121223513235241131140321304343032313200003010
        ///010010110133 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TreetopTreeHouseInput {
            get {
                return ResourceManager.GetString("TreetopTreeHouseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzsspbssbhshchmmrmprmrfrsfrrjhjphjjtppbfflqfqppdhdbhdhbbjgghgzgsgfsfhfhvvwcwhwwnppsbsggqnnvvtffpssjfjnnltntdtdddptprppjmmqssrlrplllfrrzggbmmlmnmtnnzddfdgfdfsstbstbbzcbbcjcvvfwwwzlzssglsgllnbnmbnmbbgmmppmwwsrrzqqvgqgnqnmmswwrnnbsnnbdbwwqnwqnwwzzqwzqzjqqwbqbccjcwwjlwjwppqfqjffwddrzrjzrjzzzhchjjlqqrggzvvnlvnvjvhvnvjvbbvdvldldbbwddtsscbbhccmbmbppbmmgjggcjjlrrwjwtjwwmffgddwvdvbdbvvhchmhmdmwwbjbjcbbcmbmmslmlslsjjrnrjrjpjcjgcjcjbbwsbsbfssjzsjsggcmcsswgssbbqpbqqdsdqqztzmzpmpbmbvbjjtrjtthwhbhnbhnbnssvpvsppgrrcwrrmqq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TuningTroubleInput {
            get {
                return ResourceManager.GetString("TuningTroubleInput", resourceCulture);
            }
        }
    }
}
